os:
  - linux
  - osx

branches:
  only:
    - master

env:
  - NODE_VERSION="4.2.1"

script:
  - chmod a+x ./script/travis-build.sh
  - ./script/travis-build.sh
  - npm install
  - sleep 3
  - npm install
  - sleep 3
  - npm run compileScripts
  - sleep 10
  - npm test
  - cat /home/travis/build/arkenthera/Chiika/logs/log.txt


cache:
  directories:
    - node_modules

notifications:
  email:
    recipients: arkenthera@gmail.com
  on_success: always
  on_failure: always
