os:
  - linux
  - osx


branches:
  only:
    - master

env:
  - NODE_VERSION="5.4.1"

before_install:
 - chmod +x ./travis-build.sh

script:
  - ./travis-build.sh
  - mocha --compilers coffee:coffee-script/register ./spec/app-spec.coffee

cache:
  directories:
    - node_modules

notifications:
  email:
    recipients: arkenthera@gmail.com
  on_success: always
  on_failure: always
