language: node_js

node_js: "4"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - mkdir .serve
  - gulp compile:scripts:not:watch
  - ls .serve
  - ls .serve/main_process
  - npm test

branches:
  only:
    - master

cache:
  directories:
    - node_modules

notifications:
  email:
    recipients: arkenthera@gmail.com
  on_success: always
  on_failure: always
