os:
  - linux
  - osx

branches:
  only:
    - master

env:
  - NODE_VERSION="4.2.1"

install:
  - chmod a+x ./script/travis-build.sh

script:
  - ./script/travis-build.sh
  - npm test



notifications:
  email:
    recipients: arkenthera@gmail.com
  on_success: always
  on_failure: always
