os:
  - linux
  - osx


branches:
  only:
    - master

env:
  - NODE_VERSION="4.2.1"

before_install:
 - chmod +x ./travis-build.sh

script:
  - ./travis-build.sh

cache:
  directories:
    - node_modules
