os:
  - linux
  - osx

branches:
  only:
    - master

env:
  - NODE_VERSION="4.2.1"

script: ./script/travis-build.sh

cache:
  directories:
    - node_modules

notifications:
  email:
    recipients: arkenthera@gmail.com
  on_success: always
  on_failure: always
